name: microBlooM
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.23.4
  - matplotlib=3.6.2
  - scipy=1.9.3
  - python-igraph=0.10.2
  - pandas=1.5.1
  - pyamg=4.2.3
  - jupyter
